replicaCount: 3

image:
  repository: ajaysubhashsatti/devops-platform
  tag: latest

service:
  type: ClusterIP
  port: 80

containerPort: 5000

env:
  ENV: dev

ingress:
  enabled: true
  host: devops.local